import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { LoaderCircle, Plus, ShieldCheck, UserRoundCheck, UserRoundX } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { EmptyState, ErrorState, Loading } from '../components/Feedback';
import { Modal } from '../components/Modal';
import { useToast } from '../contexts/ToastContext';
import { api } from '../lib/api';
import { display, formatDate } from '../lib/labels';
import type { User } from '../types';

const channelLabels: Record<string, string> = { WECHAT: '微信', WHATSAPP: 'WhatsApp', PHONE: '电话', EMAIL: '邮箱' };
const initialForm = { name: '', mobile: '', email: '', password: '', role: 'SALES', channelCapabilities: ['WHATSAPP', 'EMAIL'] as string[] };

export function UsersPage() {
  const toast = useToast();
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(initialForm);
  const users = useQuery({ queryKey: ['users'], queryFn: () => api<User[]>('/users') });
  const create = useMutation({ mutationFn: () => api('/users', { method: 'POST', body: JSON.stringify({ ...form, email: form.email || undefined }) }), onSuccess: async () => { toast('账号已创建'); setForm(initialForm); setOpen(false); await queryClient.invalidateQueries({ queryKey: ['users'] }); }, onError: (error) => toast(error instanceof Error ? error.message : '创建失败', 'error') });
  const toggle = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api(`/users/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }), onSuccess: async () => { toast('账号状态已更新'); await queryClient.invalidateQueries({ queryKey: ['users'] }); }, onError: (error) => toast(error instanceof Error ? error.message : '操作失败', 'error') });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); };

  if (users.isLoading) return <Loading label="正在加载账号" />;
  if (users.error) return <ErrorState error={users.error} retry={() => void users.refetch()} />;

  return <div className="space-y-5"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-brand">团队与权限</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-ink">销售与账号</h2><p className="mt-1 text-sm text-muted">维护登录账号、沟通渠道能力和启用状态。</p></div><button className="btn-primary self-start" onClick={() => setOpen(true)}><Plus className="h-4 w-4" />创建账号</button></section>{!users.data?.length ? <EmptyState title="暂无账号" /> : <div className="grid gap-3 lg:grid-cols-2">{users.data.map((item) => <article className="surface p-5" key={item.id}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center rounded-full ${item.status === 'DISABLED' ? 'bg-slate-100 text-slate-500' : 'bg-blue-50 text-brand'}`}>{item.role === 'ADMIN' ? <ShieldCheck className="h-5 w-5" /> : <UserRoundCheck className="h-5 w-5" />}</span><div><h3 className="font-semibold text-ink">{item.name}</h3><p className="mt-0.5 text-sm text-muted">{item.role === 'ADMIN' ? '管理员' : '销售'} · {item.mobile}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === 'DISABLED' ? 'bg-slate-100 text-slate-600' : 'bg-emerald-50 text-emerald-700'}`}>{item.status === 'DISABLED' ? '已停用' : '正常'}</span></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-muted">邮箱</dt><dd className="mt-1 font-medium">{display(item.email)}</dd></div><div><dt className="text-xs text-muted">名下客户</dt><dd className="mt-1 font-medium">{item._count?.assignedLeads ?? 0}</dd></div><div><dt className="text-xs text-muted">擅长渠道</dt><dd className="mt-1 font-medium">{item.channelCapabilities?.map((value) => channelLabels[value]).join('、') || '未设置'}</dd></div><div><dt className="text-xs text-muted">最后登录</dt><dd className="mt-1 font-medium">{formatDate(item.lastLoginAt)}</dd></div></dl><button className="btn-secondary mt-5 w-full" onClick={() => toggle.mutate({ id: item.id, status: item.status === 'DISABLED' ? 'ACTIVE' : 'DISABLED' })}>{item.status === 'DISABLED' ? <UserRoundCheck className="h-4 w-4" /> : <UserRoundX className="h-4 w-4" />}{item.status === 'DISABLED' ? '启用账号' : '停用账号'}</button></article>)}</div>}
    <Modal open={open} title="创建账号" onClose={() => setOpen(false)} footer={<><button className="btn-secondary" onClick={() => setOpen(false)}>取消</button><button className="btn-primary" form="create-user-form" disabled={create.isPending}>{create.isPending && <LoaderCircle className="h-4 w-4 animate-spin" />}创建账号</button></>}><form id="create-user-form" className="space-y-4" onSubmit={submit}><label className="block"><span className="label">姓名</span><input className="field" required value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></label><label className="block"><span className="label">手机号</span><input className="field" required value={form.mobile} onChange={(event) => setForm((current) => ({ ...current, mobile: event.target.value }))} /></label><label className="block"><span className="label">邮箱</span><input className="field" type="email" value={form.email} onChange={(event) => setForm((current) => ({ ...current, email: event.target.value }))} /></label><label className="block"><span className="label">初始密码（至少12位）</span><input className="field" type="password" minLength={12} required value={form.password} onChange={(event) => setForm((current) => ({ ...current, password: event.target.value }))} /></label><label className="block"><span className="label">角色</span><select className="field" value={form.role} onChange={(event) => setForm((current) => ({ ...current, role: event.target.value }))}><option value="SALES">销售</option><option value="ADMIN">管理员</option></select></label>{form.role === 'SALES' && <fieldset><legend className="label">擅长沟通渠道</legend><div className="grid grid-cols-2 gap-2">{Object.entries(channelLabels).map(([value, label]) => <label className="flex min-h-11 items-center gap-2 rounded-md border border-line px-3 text-sm" key={value}><input type="checkbox" checked={form.channelCapabilities.includes(value)} onChange={(event) => setForm((current) => ({ ...current, channelCapabilities: event.target.checked ? [...current.channelCapabilities, value] : current.channelCapabilities.filter((item) => item !== value) }))} />{label}</label>)}</div></fieldset>}</form></Modal>
  </div>;
}
